# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetcode" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "265d0bbce3dcdda7fda5c833e2a653725a961082173b49bac44c19d1f2eb465c"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79cfea9da65b5d7bdf74eef176e9771db5a67447f4dd9e4df8ff87776d95fd0c"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f51979efa815a0f1cd9ca326ababb59b978d6c2daceccd11d3be6e90e7e36d26"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c403f80b46af65d5b2d50d9ac1da4b1378fe066504a47e5f4815665b0140e480"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leetcode"
  desc "Terminal CLI for public LeetCode profile statistics."
  homepage "https://github.com/adityasgit25/leetcodecli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetcode"

  # No zap stanza required

  caveats <<~EOS
    Run `leetcode help` after installation.
  EOS
end
