# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetcode" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "10098afd5c8c77682823045b8ed717aefdd6e774e248934b1cfa0996c7aa5a92"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "19c36ea247ae21bcec442ea826062141464e010b8d84fa742ca8e279a5ba62f2"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57c9d4e3b5e82d8085115274efd2733e3cff9f75c8869b35c0171d0bc1dd0477"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e11af3f6c8dbc10b5047048179cb08cf2b5f110a1772ffd1498166994c1b7223"
      url "https://github.com/adityasgit25/leetcodecli/releases/download/v#{version}/leetcode_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leetcode"
  desc "Terminal CLI for public LeetCode profile statistics."
  homepage "https://github.com/adityasgit25/leetcodecli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetcode"

  postflight do
    system_command "#{staged_path}/leetcode", args: ["help"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `leetcode help` after installation.
  EOS
end
